include = ["*.toml"]

[formatting]
indent_string = "    "
reorder_keys = false

[[rule]]
include = ["Cargo.toml"]
keys = ["dependencies", "lints.clippy", "lints.rust"]

[rule.formatting]
reorder_keys = true
reorder_arrays = true
