name: CI - Code Checks & Tests

on:
  push:
    branches-ignore:
      - "wip*"
    paths:
      - ".github/workflows/code_check.yml"
      - "Cargo.*"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/code_check.yml"
      - "Cargo.*"
      - "src/**"

concurrency:
  # For a given workflow, if we push to the same branch, cancel all previous builds on that branch.
  # Particularly useful for workflow triggered on release-plz sync.
  # release-plz workflow update de pending pr twice (with cargo readme update)
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  rust_checks_and_tests:
    runs-on: ubuntu-latest
    name: Rust Checks and Tests
    steps:
      - name: "Install rust-toolchain stable"
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: "Show environment"
        run: |
          rustc -vV
          cargo -vV

      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true # useful for don't rebuild cargo-readme and dependencies on fix after failure

      - name: "Cargo formatting"
        if: $${{ always() }}
        run: cargo fmt --all -- --check

      - name: Check if readme is up to date
        if: $${{ always() }}
        run: |
          cargo install cargo-readme --locked
          diff README.md <(cargo readme)

      - name: "Cargo doc"
        env:
          RUSTDOCFLAGS: "-D warnings"
        if: $${{ always() }}
        run: cargo doc --locked

      - name: "Cargo clippy"
        if: $${{ always() }}
        run: cargo clippy --profile=test --locked

      - name: "Cargo test"
        if: $${{ always() }}
        run: cargo test --locked

  typos_checks:
    runs-on: ubuntu-latest
    name: Typos check
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: Check spelling of entire workspace
        uses: crate-ci/typos@master

  toml_checks:
    runs-on: ubuntu-latest
    name: Toml check
    steps:
      - uses: actions/checkout@v6

      - name: "Cargo.toml format"
        if: $${{ always() }}
        uses: gwen-lg/taplo-action@v1
        with:
          format: true
          lint: false

      - name: "Cargo.toml lint"
        if: $${{ always() }}
        uses: gwen-lg/taplo-action@v1
        with:
          format: false
          lint: true
